name: discord-components-core
org: Welcomer-Bot
install: true
packagePath: packages/core
identifierBase: false
tagTemplate: 'v{{new-version}}'
monoRepo: false
pushTag: true
gitRepo: Welcomer-Bot/discord-components
gitHostVariant: github
githubRelease: true
githubReleaseLatest: true
githubReleaseNameTemplate: '{{new-version}}'
